kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/balance: random
spec:
  to:
    kind: Service
    name: user19-hello-chart-service
    weight: 50
  alternateBackends:
  - kind: Service
    name: user19-hello-world
    weight: 50